name: "Build and release"

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: "ubuntu-latest"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
      - name: "Build & release"
        run: |
          ./release.sh
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
              dist/*
